package model.hibernate.dto;
// Generated Oct 24, 2022 12:23:58 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * TipoNoticia generated by hbm2java
 */
@Entity(name="tipo_noticia")
public class TipoNoticia  implements java.io.Serializable {

    @Id 
    private Integer idTipoNoticia;
    private String descripcion;
    private Set noticias = new HashSet(0);

    public TipoNoticia() {
    }

	
    public TipoNoticia(String descripcion) {
        this.descripcion = descripcion;
    }
    public TipoNoticia(String descripcion, Set noticias) {
       this.descripcion = descripcion;
       this.noticias = noticias;
    }
   
    public Integer getIdTipoNoticia() {
        return this.idTipoNoticia;
    }
    
    public void setIdTipoNoticia(Integer idTipoNoticia) {
        this.idTipoNoticia = idTipoNoticia;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getNoticias() {
        return this.noticias;
    }
    
    public void setNoticias(Set noticias) {
        this.noticias = noticias;
    }




}


